#!/usr/bin/env nu
# Regenerate the coupled generated module artifacts from `experiment_module`. Run inside
# the flake devshell so SPACETIMEDB_2_7_0_BIN is set
# (e.g. `direnv exec . scripts/generate.nu`). Rerun whenever `experiment_module` changes.
#
# Provenance chain (why this exists): build the module WASM once, hash THAT exact
# artifact into a committed constant, and generate the committed bindings from the SAME
# artifact using the absolute pinned `spacetimedb-cli` (never ambient `spacetime`). At
# runtime the harness re-reads the built WASM, verifies its hash against the committed
# constant, and publishes exactly those verified bytes — so the committed bindings, the
# committed hash, and the published bytes all correspond, with no committed binary.
#
# All coupled outputs live under one generated tree, `experiment_harness/src/module_artifact/`:
#   mod.rs                 declarative module (bindings + hash constant)
#   module_wasm_sha256.rs  the provenance hash constant
#   bindings/              `spacetimedb-cli generate` output
#
# The replacement is atomic: the complete tree is built in a same-filesystem staging
# directory, then swapped in via checked rename with old->backup and rollback on failure;
# the backup is removed only after success.

def main [] {
    let repo = ($env.FILE_PWD | path dirname)

    # Explicit env-key presence check — no default.
    if ("SPACETIMEDB_2_7_0_BIN" not-in $env) {
        error make { msg: "SPACETIMEDB_2_7_0_BIN is unset — run inside the flake devshell (direnv exec .)" }
    }
    let bin = $env.SPACETIMEDB_2_7_0_BIN
    let cli = ([$bin "spacetimedb-cli"] | path join)
    if not ($cli | path exists) {
        error make { msg: $"pinned spacetimedb-cli not found at ($cli)" }
    }

    let wasm = ([$repo "target/wasm32-unknown-unknown/release/experiment_module.wasm"] | path join)
    let src = ([$repo "experiment_harness/src"] | path join)
    let final = ([$src "module_artifact"] | path join)
    let staged = ([$src ".module_artifact.staged"] | path join)
    let backup = ([$src ".module_artifact.backup"] | path join)

    # State-aware recovery of a prior interrupted swap, BEFORE touching staging.
    # The swap sequence is: (a) mv final -> backup, (b) mv staged -> final, (c) rm backup.
    let final_exists = ($final | path exists)
    let backup_exists = ($backup | path exists)
    if (not $final_exists) and $backup_exists {
        # Interrupted between (a) and (b): backup is the only good tree — restore it.
        print "recovering: restoring backup -> final"
        mv $backup $final
    } else if $final_exists and $backup_exists {
        # Interrupted between (b) and (c): final is the completed replacement, backup is stale.
        print "recovering: removing stale backup (final already complete)"
        rm -rf $backup
    }
    # Remaining states need no recovery: (final present, backup absent) = steady state;
    # (both absent) = first generation. After recovery, a lingering backup is impossible.
    if ($backup | path exists) {
        error make { msg: $"unrecoverable generator state: backup still present at ($backup) after recovery" }
    }

    # Staging is never the authoritative tree — discard any leftover from an aborted run.
    rm -rf $staged

    # 1. Build the module WASM (release, wasm target).
    print "building experiment_module wasm..."
    cd $repo
    cargo build -p experiment_module --target wasm32-unknown-unknown --release

    # 2. Hash that exact artifact.
    let digest = (open --raw $wasm | hash sha256)
    print $"module wasm sha256 = ($digest)"

    # 3. Build the complete replacement tree in staging (same filesystem as `final`).
    mkdir $staged
    let bindings = ([$staged "bindings"] | path join)
    mkdir $bindings
    print $"generating bindings into ($bindings)..."
    ^$cli generate --lang rust --out-dir $bindings --bin-path $wasm

    let bytes = ($digest | split chars | chunks 2 | each {|p| $"0x($p | str join)" } | str join ", ")
    let hash_header = ("//! GENERATED by scripts/generate.nu — DO NOT EDIT BY HAND.\n" +
        "//!\n" +
        "//! SHA-256 of the `experiment_module` WASM that the sibling `bindings` were produced\n" +
        "//! from. The harness verifies the built WASM against this constant before publishing,\n" +
        "//! so the bindings and the published bytes provably correspond.\n")
    ($"($hash_header)\npub const MODULE_WASM_SHA256: [u8; 32] = [($bytes)];\n"
        | save -f ([$staged "module_wasm_sha256.rs"] | path join))

    let mod_rs = ("//! GENERATED by scripts/generate.nu — DO NOT EDIT BY HAND.\n" +
        "//!\n" +
        "//! Coupled generated artifacts for the experiment module: the SpacetimeDB client\n" +
        "//! `bindings` and the `module_wasm_sha256` provenance constant, produced together from\n" +
        "//! one WASM build so they always correspond.\n" +
        "\n" +
        "pub mod bindings;\n" +
        "pub mod module_wasm_sha256;\n")
    ($mod_rs | save -f ([$staged "mod.rs"] | path join))

    # 4. Checked swap: final -> backup, staged -> final; rollback on failure.
    let had_final = ($final | path exists)
    try {
        if $had_final { mv $final $backup }
        mv $staged $final
    } catch {|e|
        if $had_final and ($backup | path exists) and (not ($final | path exists)) {
            mv $backup $final
        }
        rm -rf $staged
        error make { msg: $"generated swap failed, rolled back: ($e.msg)" }
    }

    # 5. Success: drop backup and any legacy flat-layout outputs.
    rm -rf $backup
    rm -rf ([$src "generated"] | path join)
    rm -rf ([$src "module_wasm_sha256.rs"] | path join)

    print $"replaced ($final)"
    print "done."
}
